import {
  BookOpen,
  Brain,
  Database,
  Code2,
  Wrench,
  Rocket,
  Radar,
  ShieldAlert,
  Lock,
  Lightbulb,
  FlaskConical,
  Wifi,
  Globe2,
  Microscope,
  Network,
  GraduationCap,
  Users,
  Shield,
  Presentation,
  CalendarDays,
  Globe,
  Bug,
  FileText,
  Gamepad2,
  Cloud,
  Cpu,
  Server,
  Smartphone,
  PartyPopper,
  KeyRound,
  Video,
  ShieldCheck,
  StickyNote,
  Eye,
  Hammer,
  Map,
} from "lucide-react";

const ACTIVITY_ICON_MAP = {
  brain: Brain,
  database: Database,
  code: Code2,
  wrench: Wrench,
  rocket: Rocket,
  radar: Radar,
  "shield-alert": ShieldAlert,
  lock: Lock,
  lightbulb: Lightbulb,
  "flask-conical": FlaskConical,
  wifi: Wifi,
  "globe-2": Globe2,
  "graduation-cap": GraduationCap,
  microscope: Microscope,
  users: Users,
  "party-popper": PartyPopper,
  "calendar-days": CalendarDays,
  presentation: Presentation,
  "sticky-note": StickyNote,
  globe: Globe,
  eye: Eye,
  bug: Bug,
  server: Server,
  network: Network,
  cloud: Cloud,
  cpu: Cpu,
  "file-text": FileText,
  "gamepad-2": Gamepad2,
  "key-round": KeyRound,
  video: Video,
  "shield-check": ShieldCheck,
  map: Map,
  smartphone: Smartphone,
  hammer: Hammer,
  "book-open": BookOpen,
  shield: Shield,
} as const;

const ACTIVITY_ICON_KEYS = Object.keys(ACTIVITY_ICON_MAP);

function getActivityIconByKey(key?: string | null) {
  if (!key) return Shield;
  return ACTIVITY_ICON_MAP[key] ?? Shield;
}

export { ACTIVITY_ICON_KEYS, ACTIVITY_ICON_MAP, getActivityIconByKey };
